vich_uploader:
    db_driver: orm

    mappings:
       habitats:
           uri_prefix: /images/habitats
           upload_destination: '%kernel.project_dir%/public/images/habitats'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
