<?php

namespace ContainerK82Kant;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2NzmnZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2_NzmnZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2_NzmnZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'city' => ['privates', '.errored..service_locator.2_NzmnZ.App\\Entity\\Ville', NULL, 'Cannot autowire service ".service_locator.2_NzmnZ": it needs an instance of "App\\Entity\\Ville" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'city' => 'App\\Entity\\Ville',
            'em' => '?',
        ]);
    }
}
