#index:
#    path: /
#    controller: App\Controller\DefaultController::index


user_list:
    path: /users
    controller: App\Controller\UserController::index
    methods: GET

user_create:
    path: /users
    controller: App\Controller\UserController::createUser
    methods: POST

user_show:
    path: /users/{id}
    controller: App\Controller\UserController::readUser
    methods: GET

user_update:
    path: /users/{id}
    controller: App\Controller\UserController::updateUser
    methods: PUT

user_delete:
    path: /users/{id}
    controller: App\Controller\UserController::deleteUser
    methods: DELETE
