<?php

namespace ContainerWqpbjI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaysService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1dW180q.App\Entity\Pays' shared service.
     *
     * @return \App\Entity\Pays
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1dW180q": it needs an instance of "App\\Entity\\Pays" but this type has been excluded in "config/services.yaml".');
    }
}
