<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNZBQfVe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNZBQfVe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNZBQfVe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNZBQfVe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNZBQfVe\App_KernelDevDebugContainer([
    'container.build_hash' => 'NZBQfVe',
    'container.build_id' => '63ee0443',
    'container.build_time' => 1717202582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNZBQfVe');
