<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvCOlKU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvCOlKU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSvCOlKU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSvCOlKU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSvCOlKU\App_KernelDevDebugContainer([
    'container.build_hash' => 'SvCOlKU',
    'container.build_id' => 'dfa7e7b8',
    'container.build_time' => 1717195969,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvCOlKU');
